FILTER_SONGS = ["Drums", "Space"]

TOP_SONGS = 50
TOP_SONGS_BY_YEAR = 10
TOP_SONGS_BY_MONTH = 10
TOP_SONGS_BY_DAY = 10

NUM_TOP_SETS = 2
NUM_TOP_ENCORES = 25

NUM_TOP_SET_SONGS = 50

NUM_TOP_COVERS = 20