# Generated by Django 2.0.5 on 2018-05-31 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('orig_artist', models.CharField(max_length=200)),
                ('sets', models.ManyToManyField(to='stats.Set')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('state_code', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=25)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fips', models.CharField(max_length=10)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Concert')),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='encores',
            field=models.ManyToManyField(to='stats.Song'),
        ),
        migrations.AddField(
            model_name='concert',
            name='sets',
            field=models.ManyToManyField(to='stats.Set'),
        ),
        migrations.AddField(
            model_name='concert',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Tour'),
        ),
    ]
