# Generated by Django 2.0.5 on 2018-05-31 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='concert',
        ),
        migrations.AddField(
            model_name='concert',
            name='venue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stats.Venue'),
        ),
        migrations.AlterField(
            model_name='song',
            name='orig_artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stats.Artist'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state_code',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stats.Artist'),
        ),
    ]
