# Generated by Django 2.0.5 on 2018-05-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20180531_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='sets',
        ),
        migrations.AddField(
            model_name='set',
            name='songs',
            field=models.ManyToManyField(to='stats.Song'),
        ),
    ]
