# Generated by Django 2.0.5 on 2018-06-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20180531_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlistfmstatus',
            name='exists',
            field=models.BooleanField(default=True),
        ),
    ]
