# Generated by Django 2.0.5 on 2018-06-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_setlistfmstatus_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlistfmstatus',
            name='alerted',
            field=models.BooleanField(default=False),
        ),
    ]
