# Generated by Django 2.0.5 on 2018-06-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_setlistfmstatus_alerted'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='mbid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
